global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "cybersentinel-api"
    static_configs:
      - targets: ["cybersentinel-api:8080"]
